//Verilog instantiation template

pcie2_core _inst (.pcie2_x1_bus_num(), .pcie2_x1_class_code(), .pcie2_x1_cmd_reg_out(), 
           .pcie2_x1_dev_cntl_2_out(), .pcie2_x1_dev_cntl_out(), .pcie2_x1_dev_num(), 
           .pcie2_x1_device_id(), .pcie2_x1_func_num(), .pcie2_x1_hl_gto_lbk(), 
           .pcie2_x1_lnk_cntl_out(), .pcie2_x1_mm_enable(), .pcie2_x1_msi(), 
           .pcie2_x1_npd_num_vc0(), .pcie2_x1_pd_num_vc0(), .pcie2_x1_phy_cfgln(), 
           .pcie2_x1_phy_cfgln_sum(), .pcie2_x1_phy_ltssm_state(), .pcie2_x1_pm_power_state(), 
           .pcie2_x1_rev_id(), .pcie2_x1_rx_bar_hit(), .pcie2_x1_rx_data_vc0(), 
           .pcie2_x1_rx_lbk_data(), .pcie2_x1_rx_lbk_kcntl(), .pcie2_x1_rxdp_dllp_val(), 
           .pcie2_x1_rxdp_pmd_type(), .pcie2_x1_rxdp_vsd_data(), .pcie2_x1_subsys_id(), 
           .pcie2_x1_subsys_ven_id(), .pcie2_x1_tx_ca_cpld_vc0(), .pcie2_x1_tx_ca_cplh_vc0(), 
           .pcie2_x1_tx_ca_npd_vc0(), .pcie2_x1_tx_ca_nph_vc0(), .pcie2_x1_tx_ca_pd_vc0(), 
           .pcie2_x1_tx_ca_ph_vc0(), .pcie2_x1_tx_data_vc0(), .pcie2_x1_tx_dllp_val(), 
           .pcie2_x1_tx_lbk_data(), .pcie2_x1_tx_lbk_kcntl(), .pcie2_x1_tx_pmtype(), 
           .pcie2_x1_tx_vsd_data(), .pcie2_x1_vendor_id(), .pcie2_x1_cmpln_tout(), 
           .pcie2_x1_cmpltr_abort_np(), .pcie2_x1_cmpltr_abort_p(), .pcie2_x1_dl_active(), 
           .pcie2_x1_dl_inactive(), .pcie2_x1_dl_init(), .pcie2_x1_dl_up(), 
           .pcie2_x1_flip_lanes(), .pcie2_x1_flr_rdy_in(), .pcie2_x1_force_disable_scr(), 
           .pcie2_x1_force_lsm_active(), .pcie2_x1_force_phy_status(), .pcie2_x1_force_rec_ei(), 
           .pcie2_x1_hdinn0(), .pcie2_x1_hdinp0(), .pcie2_x1_hdoutn0(), 
           .pcie2_x1_hdoutp0(), .pcie2_x1_hl_disable_scr(), .pcie2_x1_hl_gto_cfg(), 
           .pcie2_x1_hl_gto_det(), .pcie2_x1_hl_gto_dis(), .pcie2_x1_hl_gto_hrst(), 
           .pcie2_x1_hl_gto_l0stx(), .pcie2_x1_hl_gto_l0stxfts(), .pcie2_x1_hl_gto_l1(), 
           .pcie2_x1_hl_gto_l2(), .pcie2_x1_hl_gto_rcvry(), .pcie2_x1_hl_snd_beacon(), 
           .pcie2_x1_initiate_flr(), .pcie2_x1_inta_n(), .pcie2_x1_load_id(), 
           .pcie2_x1_msi_enable(), .pcie2_x1_no_pcie_train(), .pcie2_x1_np_req_pend(), 
           .pcie2_x1_npd_buf_status_vc0(), .pcie2_x1_npd_processed_vc0(), 
           .pcie2_x1_nph_buf_status_vc0(), .pcie2_x1_nph_processed_vc0(), 
           .pcie2_x1_pd_buf_status_vc0(), .pcie2_x1_pd_processed_vc0(), 
           .pcie2_x1_ph_buf_status_vc0(), .pcie2_x1_ph_processed_vc0(), 
           .pcie2_x1_phy_pol_compliance(), .pcie2_x1_pll_refclki(), .pcie2_x1_pme_en(), 
           .pcie2_x1_pme_status(), .pcie2_x1_rst_n(), .pcie2_x1_rx_dwen_vc0(), 
           .pcie2_x1_rx_end_vc0(), .pcie2_x1_rx_malf_tlp_vc0(), .pcie2_x1_rx_st_vc0(), 
           .pcie2_x1_rx_us_req_vc0(), .pcie2_x1_rxrefclk(), .pcie2_x1_sys_clk_125(), 
           .pcie2_x1_tx_ca_cpl_recheck_vc0(), .pcie2_x1_tx_ca_p_recheck_vc0(), 
           .pcie2_x1_tx_dllp_sent(), .pcie2_x1_tx_dwen_vc0(), .pcie2_x1_tx_end_vc0(), 
           .pcie2_x1_tx_lbk_rdy(), .pcie2_x1_tx_nlfy_vc0(), .pcie2_x1_tx_rdy_vc0(), 
           .pcie2_x1_tx_req_vc0(), .pcie2_x1_tx_st_vc0(), .pcie2_x1_tx_val(), 
           .pcie2_x1_unexp_cmpln(), .pcie2_x1_ur_np_ext(), .pcie2_x1_ur_p_ext(), 
           .pcie2_extref_refclkn(), .pcie2_extref_refclko(), .pcie2_extref_refclkp());