//Verilog instantiation template

pcie_core _inst (.pcie_extref_refclkn(), .pcie_extref_refclkp(), .pcie_x1_bus_num(), 
          .pcie_x1_class_code(), .pcie_x1_cmd_reg_out(), .pcie_x1_dev_cntl_out(), 
          .pcie_x1_dev_num(), .pcie_x1_device_id(), .pcie_x1_func_num(), 
          .pcie_x1_lnk_cntl_out(), .pcie_x1_mm_enable(), .pcie_x1_msi(), 
          .pcie_x1_npd_num_vc0(), .pcie_x1_pd_num_vc0(), .pcie_x1_phy_ltssm_state(), 
          .pcie_x1_pm_power_state(), .pcie_x1_rev_id(), .pcie_x1_rx_bar_hit(), 
          .pcie_x1_rx_data_vc0(), .pcie_x1_rx_lbk_data(), .pcie_x1_rx_lbk_kcntl(), 
          .pcie_x1_rxdp_dllp_val(), .pcie_x1_rxdp_pmd_type(), .pcie_x1_rxdp_vsd_data(), 
          .pcie_x1_sci_addr(), .pcie_x1_sci_rddata(), .pcie_x1_sci_wrdata(), 
          .pcie_x1_subsys_id(), .pcie_x1_subsys_ven_id(), .pcie_x1_tx_ca_cpld_vc0(), 
          .pcie_x1_tx_ca_cplh_vc0(), .pcie_x1_tx_ca_npd_vc0(), .pcie_x1_tx_ca_nph_vc0(), 
          .pcie_x1_tx_ca_pd_vc0(), .pcie_x1_tx_ca_ph_vc0(), .pcie_x1_tx_data_vc0(), 
          .pcie_x1_tx_dllp_val(), .pcie_x1_tx_lbk_data(), .pcie_x1_tx_lbk_kcntl(), 
          .pcie_x1_tx_pmtype(), .pcie_x1_tx_vsd_data(), .pcie_x1_vendor_id(), 
          .pcie_x1_cmpln_tout(), .pcie_x1_cmpltr_abort_np(), .pcie_x1_cmpltr_abort_p(), 
          .pcie_x1_dl_active(), .pcie_x1_dl_inactive(), .pcie_x1_dl_init(), 
          .pcie_x1_dl_up(), .pcie_x1_flip_lanes(), .pcie_x1_force_disable_scr(), 
          .pcie_x1_force_lsm_active(), .pcie_x1_force_phy_status(), .pcie_x1_force_rec_ei(), 
          .pcie_x1_hdinn0(), .pcie_x1_hdinp0(), .pcie_x1_hdoutn0(), .pcie_x1_hdoutp0(), 
          .pcie_x1_hl_disable_scr(), .pcie_x1_hl_gto_cfg(), .pcie_x1_hl_gto_det(), 
          .pcie_x1_hl_gto_dis(), .pcie_x1_hl_gto_hrst(), .pcie_x1_hl_gto_l0stx(), 
          .pcie_x1_hl_gto_l0stxfts(), .pcie_x1_hl_gto_l1(), .pcie_x1_hl_gto_l2(), 
          .pcie_x1_hl_gto_lbk(), .pcie_x1_hl_gto_rcvry(), .pcie_x1_hl_snd_beacon(), 
          .pcie_x1_inta_n(), .pcie_x1_load_id(), .pcie_x1_msi_enable(), 
          .pcie_x1_no_pcie_train(), .pcie_x1_np_req_pend(), .pcie_x1_npd_buf_status_vc0(), 
          .pcie_x1_npd_processed_vc0(), .pcie_x1_nph_buf_status_vc0(), .pcie_x1_nph_processed_vc0(), 
          .pcie_x1_pd_buf_status_vc0(), .pcie_x1_pd_processed_vc0(), .pcie_x1_ph_buf_status_vc0(), 
          .pcie_x1_ph_processed_vc0(), .pcie_x1_phy_pol_compliance(), .pcie_x1_pme_en(), 
          .pcie_x1_pme_status(), .pcie_x1_rst_n(), .pcie_x1_rx_end_vc0(), 
          .pcie_x1_rx_malf_tlp_vc0(), .pcie_x1_rx_st_vc0(), .pcie_x1_rx_us_req_vc0(), 
          .pcie_x1_sci_en(), .pcie_x1_sci_en_dual(), .pcie_x1_sci_int(), 
          .pcie_x1_sci_rd(), .pcie_x1_sci_sel(), .pcie_x1_sci_sel_dual(), 
          .pcie_x1_sci_wrn(), .pcie_x1_sys_clk_125(), .pcie_x1_tx_ca_cpl_recheck_vc0(), 
          .pcie_x1_tx_ca_p_recheck_vc0(), .pcie_x1_tx_dllp_sent(), .pcie_x1_tx_end_vc0(), 
          .pcie_x1_tx_lbk_rdy(), .pcie_x1_tx_nlfy_vc0(), .pcie_x1_tx_rdy_vc0(), 
          .pcie_x1_tx_req_vc0(), .pcie_x1_tx_st_vc0(), .pcie_x1_unexp_cmpln(), 
          .pcie_x1_ur_np_ext(), .pcie_x1_ur_p_ext());