-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.13.0.56.2
-- Module  Version: 5.7
-- Tue Apr 01 09:50:04 2025

-- parameterized module component declaration
component Module_Pll27MHz
    port (CLKI: in  std_logic; CLKOP: out  std_logic; 
        CLKOS: out  std_logic; LOCK: out  std_logic);
end component;

-- parameterized module component instance
__ : Module_Pll27MHz
    port map (CLKI=>__, CLKOP=>__, CLKOS=>__, LOCK=>__);
