PROJECT: pcie_x1
working_path: "syn_results"
module: pcie_x1
verilog_file_list: "C:/lscc/diamond/3.10_x64/cae_library/synthesis/verilog/ecp5um.v"
verilog_file_list: "C:/lscc/diamond/3.10_x64/cae_library/synthesis/verilog/pmi_def.v"
verilog_file_list: "../pcie_x1_core_bb.v"
verilog_file_list: "../pcie_x1.v"
verilog_file_list: "../pcie_eval/models/ecp5um5g/pcie_x1_pcs_softlogic.v"
verilog_file_list: "../pcie_eval/models/ecp5um5g/pcie_x1_pcs.v"
verilog_file_list: "../pcie_eval/models/ecp5um5g/pcie_x1_sync1s.v"
verilog_file_list: "../pcie_eval/models/ecp5um5g/pcie_x1_ctc.v"
verilog_file_list: "../pcie_eval/models/ecp5um5g/pcie_x1_pipe.v"
verilog_file_list: "../pcie_eval/models/ecp5um5g/pcie_x1_phy.v"
resource_sharing: false
write_verilog: true
write_vhdl: false
suffix_name: edi
output_file_name: pcie_x1
write_prf: false
vlog_std_v2001: true
disable_io_insertion: true
force_gsr: false
speed_grade: 8
frequency: 125.000
fanout_limit: 100
retiming: false
pipe: false
fixgatedclocks: 0
fixgeneratedclocks: 0
