//=============================================================================
// Verilog module generated by IPExpress    08/21/2007    16:22:41          
// Filename: pcs_pipe_bb.v                                            
// Copyright(c) 2005 Lattice Semiconductor Corporation. All rights reserved.   
//=============================================================================

/* WARNING - Changes to this file should be performed by re-running IPexpress
or modifying the .LPC file and regenerating the core.  Other changes may lead
to inconsistent simulation and/or implemenation results */

module pcie_x1_phy (
// serdes clk pins //
  pll_refclki,
  rxrefclk,
  RESET_n,
  pcie_ip_rstn,

  hdinp0,
  hdinn0,
  hdoutp0,
  hdoutn0,

  TxData_0,
  TxDataK_0,
  TxCompliance_0,  
  TxElecIdle_0,
  RxData_0,
  RxDataK_0,
  RxValid_0,
  RxPolarity_0,
  RxElecIdle_0,
  RxStatus_0,

  sci_wrdata,
  sci_addr,
  sci_rddata,
  sci_int,
  sci_en_dual,
  sci_sel_dual,
  sci_wrn,
  sci_rd,
  sci_sel,
  sci_en,
  ffs_plol,
  ffs_rlol_ch0,
  flip_lanes,
  PCLK,
  PCLK_by_2,
  TxDetectRx_Loopback, 
  PhyStatus,
  PowerDown,
  phy_l0,
  phy_cfgln,
  ctc_disable
  ) 
  /*synthesis syn_black_box black_box_pad_pin = "hdinp0, hdinn0, hdoutp0, hdoutn0" */
;
// =============================================================================
// inputs and outputs
// =============================================================================
//
//
input        pll_refclki;
input        rxrefclk;
input        RESET_n; 
output       pcie_ip_rstn;


input        hdinp0; 
input        hdinn0; 
output       hdoutp0;
output       hdoutn0;
              
input   [7:0]  TxData_0;
input   [0:0]  TxDataK_0;
input          TxCompliance_0;
input          TxElecIdle_0;
output  [7:0]  RxData_0;
output  [0:0]  RxDataK_0; 
output         RxValid_0;
input          RxPolarity_0;
output         RxElecIdle_0;
output  [2:0]  RxStatus_0;  

input [7:0]    sci_wrdata;
input [5:0]    sci_addr;
output [7:0]   sci_rddata;
output         sci_int;
input          sci_en_dual;
input          sci_sel_dual;
input          sci_wrn;
input          sci_rd;
input          sci_sel;
input          sci_en;

output         ffs_plol;
output         ffs_rlol_ch0;
input          flip_lanes;
output         PCLK;
output         PCLK_by_2;
input          TxDetectRx_Loopback;
output         PhyStatus;
input  [1:0]   PowerDown;
               
input          ctc_disable;
input          phy_l0;
input  [3:0]   phy_cfgln;

endmodule
