-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.11.3.469
-- Module  Version: 5.7
-- Sun Jun 27 19:30:57 2021

-- parameterized module component declaration
component Module_Pll27MHz
    port (CLKI: in  std_logic; CLKOP: out  std_logic; 
        CLKOS: out  std_logic; LOCK: out  std_logic);
end component;

-- parameterized module component instance
__ : Module_Pll27MHz
    port map (CLKI=>__, CLKOP=>__, CLKOS=>__, LOCK=>__);
