/* Verilog module instantiation template generated by SCUBA Diamond_3.1_Production (93) */
/* Module Version: 3.7 */
/* Fri Mar 07 14:40:14 2014 */

/* parameterized module instance */
spram_16384_16 __ (.Address( ), .Data( ), .Clock( ), .WE( ), .ClockEn( ), 
    .Reset( ), .Q( ));
