//Verilog testbench template generated by SCUBA Diamond_3.1_Production (93)
`timescale 1 ns / 1 ps
module tb;
    reg [10:0] Address = 11'b0;
    reg [15:0] Data = 16'b0;
    reg Clock = 0;
    reg WE = 0;
    reg ClockEn = 0;
    reg Reset = 0;
    wire [15:0] Q;

    integer i0 = 0, i1 = 0, i2 = 0, i3 = 0, i4 = 0, i5 = 0, i6 = 0;

    GSR GSR_INST (.GSR(1'b1));
    PUR PUR_INST (.PUR(1'b1));

    spram_16384_16 u1 (.Address(Address), .Data(Data), .Clock(Clock), .WE(WE), 
        .ClockEn(ClockEn), .Reset(Reset), .Q(Q)
    );

    initial
    begin
       Address <= 0;
      #100;
      @(Reset == 1'b0);
      for (i1 = 0; i1 < 3282; i1 = i1 + 1) begin
        @(posedge Clock);
        #1  Address <= Address + 1'b1;
      end
    end
    initial
    begin
       Data <= 0;
      #100;
      @(Reset == 1'b0);
      for (i2 = 0; i2 < 1641; i2 = i2 + 1) begin
        @(posedge Clock);
        #1  Data <= Data + 1'b1;
      end
    end
    always
    #5.00 Clock <= ~ Clock;

    initial
    begin
       WE <= 1'b0;
      @(Reset == 1'b0);
      for (i4 = 0; i4 < 1641; i4 = i4 + 1) begin
        @(posedge Clock);
        #1  WE <= 1'b1;
      end
       WE <= 1'b0;
    end
    initial
    begin
       ClockEn <= 1'b0;
      #100;
      @(Reset == 1'b0);
       ClockEn <= 1'b1;
    end
    initial
    begin
       Reset <= 1'b1;
      #100;
       Reset <= 1'b0;
    end
endmodule